; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3devkitm1]
platform = espressif32
framework = arduino
board = esp32-s3-devkitm-1
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_build.psram_type = opi
board_upload.maximum_size = 16777216
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCORE_DEBUG_LEVEL=0
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-DLV_CONF_PATH="C:\\Users\\matpo\\Documents\\platformio\\alarm_clock\\include\\lv_conf.h"
upload_speed = 921600
monitor_port = COM5
monitor_speed = 115200
monitor_filters = log2file
lib_deps = 
	moononournation/GFX Library for Arduino@1.5.5
	robtillaart/TCA9554@^0.1.2
	lvgl/lvgl@8.4.0
	earlephilhower/ESP8266Audio@2.0.0
	bblanchon/ArduinoJson@6.21.4

[platformio]
description = Alarm_clock.ino platformio test
