// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_alarm_icon_png);    // assets/alarm_icon.png
LV_IMG_DECLARE(ui_img_sole_png);    // assets/sole.png
LV_IMG_DECLARE(ui_img_luna_png);    // assets/luna.png
LV_IMG_DECLARE(ui_img_nebbia_png);    // assets/nebbia.png
LV_IMG_DECLARE(ui_img_neve_png);    // assets/neve.png
LV_IMG_DECLARE(ui_img_nuvoloso_png);    // assets/nuvoloso.png
LV_IMG_DECLARE(ui_img_temporale_png);    // assets/temporale.png
LV_IMG_DECLARE(ui_img_pioggia_png);    // assets/pioggia.png

// FONTS
LV_FONT_DECLARE(ui_font_segment);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
