// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Screen1 = NULL;
lv_obj_t *ui_time = NULL;
lv_obj_t *ui_date = NULL;
lv_obj_t *ui_weekdays = NULL;
lv_obj_t *ui_temperature = NULL;
lv_obj_t *ui_alarm1 = NULL;
lv_obj_t *ui_alarm2 = NULL;
lv_obj_t *ui_alarm3 = NULL;
lv_obj_t *ui_sun = NULL;
lv_obj_t *ui_moon = NULL;
lv_obj_t *ui_fog = NULL;
lv_obj_t *ui_snow = NULL;
lv_obj_t *ui_cloudy = NULL;
lv_obj_t *ui_rain = NULL;
lv_obj_t *ui_storm = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_time, lv_pct(77));
    lv_obj_set_height(ui_time, lv_pct(40));
    lv_obj_set_x(ui_time, 0);
    lv_obj_set_y(ui_time, 5);
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time, "00:00");
    lv_obj_set_style_text_align(ui_time, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time, &ui_font_segment, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_date, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_date, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_date, 0);
    lv_obj_set_y(ui_date, -30);
    lv_obj_set_align(ui_date, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_date, "01/01/2025");
    lv_obj_set_style_text_font(ui_date, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weekdays = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_weekdays, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_weekdays, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_weekdays, 0);
    lv_obj_set_y(ui_weekdays, 30);
    lv_obj_set_align(ui_weekdays, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_weekdays, "Wednesday");
    lv_obj_set_style_text_font(ui_weekdays, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temperature = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_temperature, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_temperature, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_temperature, -10);
    lv_obj_set_y(ui_temperature, 17);
    lv_obj_set_align(ui_temperature, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_temperature, "00°");
    lv_obj_set_style_text_font(ui_temperature, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_alarm1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_alarm1, &ui_img_alarm_icon_png);
    lv_obj_set_width(ui_alarm1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_alarm1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_alarm1, 10);
    lv_obj_set_y(ui_alarm1, 10);
    lv_obj_add_flag(ui_alarm1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST); /// Flags
    lv_obj_clear_flag(ui_alarm1, LV_OBJ_FLAG_SCROLLABLE);                     /// Flags
    lv_img_set_zoom(ui_alarm1, 200);

    ui_alarm2 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_alarm2, &ui_img_alarm_icon_png);
    lv_obj_set_width(ui_alarm2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_alarm2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_alarm2, 50);
    lv_obj_set_y(ui_alarm2, 10);
    lv_obj_add_flag(ui_alarm2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST); /// Flags
    lv_obj_clear_flag(ui_alarm2, LV_OBJ_FLAG_SCROLLABLE);                     /// Flags
    lv_img_set_zoom(ui_alarm2, 200);

    ui_alarm3 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_alarm3, &ui_img_alarm_icon_png);
    lv_obj_set_width(ui_alarm3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_alarm3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_alarm3, 90);
    lv_obj_set_y(ui_alarm3, 10);
    lv_obj_add_flag(ui_alarm3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST); /// Flags
    lv_obj_clear_flag(ui_alarm3, LV_OBJ_FLAG_SCROLLABLE);                     /// Flags
    lv_img_set_zoom(ui_alarm3, 200);

    ui_sun = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_sun, &ui_img_sole_png);
    lv_obj_set_width(ui_sun, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_sun, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_sun, -60);
    lv_obj_set_y(ui_sun, 0);
    lv_obj_set_align(ui_sun, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_sun, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST); /// Flags
    lv_obj_clear_flag(ui_sun, LV_OBJ_FLAG_SCROLLABLE);                     /// Flags
    lv_img_set_zoom(ui_sun, 170);

    ui_moon = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_moon, &ui_img_luna_png);
    lv_obj_set_width(ui_moon, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_moon, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_moon, -60);
    lv_obj_set_y(ui_moon, 0);
    lv_obj_set_align(ui_moon, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_moon, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST); /// Flags
    lv_obj_clear_flag(ui_moon, LV_OBJ_FLAG_SCROLLABLE);                     /// Flags
    lv_img_set_zoom(ui_moon, 170);

    ui_fog = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_fog, &ui_img_nebbia_png);
    lv_obj_set_width(ui_fog, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_fog, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_fog, -60);
    lv_obj_set_y(ui_fog, 0);
    lv_obj_set_align(ui_fog, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_fog, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST); /// Flags
    lv_obj_clear_flag(ui_fog, LV_OBJ_FLAG_SCROLLABLE);                     /// Flags
    lv_img_set_zoom(ui_fog, 170);

    ui_snow = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_snow, &ui_img_neve_png);
    lv_obj_set_width(ui_snow, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_snow, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_snow, -60);
    lv_obj_set_y(ui_snow, 0);
    lv_obj_set_align(ui_snow, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_snow, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST); /// Flags
    lv_obj_clear_flag(ui_snow, LV_OBJ_FLAG_SCROLLABLE);                     /// Flags
    lv_img_set_zoom(ui_snow, 170);

    ui_cloudy = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_cloudy, &ui_img_nuvoloso_png);
    lv_obj_set_width(ui_cloudy, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_cloudy, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_cloudy, -60);
    lv_obj_set_y(ui_cloudy, 0);
    lv_obj_set_align(ui_cloudy, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_cloudy, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST); /// Flags
    lv_obj_clear_flag(ui_cloudy, LV_OBJ_FLAG_SCROLLABLE);                     /// Flags
    lv_img_set_zoom(ui_cloudy, 170);

    ui_rain = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_rain, &ui_img_temporale_png);
    lv_obj_set_width(ui_rain, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_rain, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_rain, -60);
    lv_obj_set_y(ui_rain, 0);
    lv_obj_set_align(ui_rain, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_rain, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST); /// Flags
    lv_obj_clear_flag(ui_rain, LV_OBJ_FLAG_SCROLLABLE);                     /// Flags
    lv_img_set_zoom(ui_rain, 170);

    ui_storm = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_storm, &ui_img_pioggia_png);
    lv_obj_set_width(ui_storm, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_storm, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_storm, -60);
    lv_obj_set_y(ui_storm, 0);
    lv_obj_set_align(ui_storm, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_storm, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST); /// Flags
    lv_obj_clear_flag(ui_storm, LV_OBJ_FLAG_SCROLLABLE);                     /// Flags
    lv_img_set_zoom(ui_storm, 170);
}

void ui_Screen1_screen_destroy(void)
{
    if (ui_Screen1)
        lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_time = NULL;
    ui_date = NULL;
    ui_weekdays = NULL;
    ui_temperature = NULL;
    ui_alarm1 = NULL;
    ui_alarm2 = NULL;
    ui_alarm3 = NULL;
    ui_sun = NULL;
    ui_moon = NULL;
    ui_fog = NULL;
    ui_snow = NULL;
    ui_cloudy = NULL;
    ui_rain = NULL;
    ui_storm = NULL;
}
