// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_date;
extern lv_obj_t * ui_weekdays;
extern lv_obj_t * ui_temperature;
extern lv_obj_t * ui_alarm1;
extern lv_obj_t * ui_alarm2;
extern lv_obj_t * ui_alarm3;
extern lv_obj_t * ui_sun;
extern lv_obj_t * ui_moon;
extern lv_obj_t * ui_fog;
extern lv_obj_t * ui_snow;
extern lv_obj_t * ui_cloudy;
extern lv_obj_t * ui_rain;
extern lv_obj_t * ui_storm;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

